// <auto-generated />
using System;
using KellyServices.PARS.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KellyServices.PARS.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715173733_AddPayrollRequests")]
    partial class AddPayrollRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ArchiveDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("EmployeeArchiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveDocumentId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ActorId", "OccurredAt");

                    b.HasIndex("EmployeeArchiveId", "OccurredAt");

                    b.ToTable("ArchiveAuditEvents", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("DocumentYear")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeArchiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceChecksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("StoredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IngestionBatchId");

                    b.HasIndex("BlobContainer", "BlobName")
                        .IsUnique();

                    b.HasIndex("SourcePath", "SourceChecksum")
                        .IsUnique();

                    b.HasIndex("EmployeeArchiveId", "DocumentYear", "DocumentType");

                    b.ToTable("ArchiveDocuments", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveFulfillment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchiveDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PayrollDataRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PayrollDataRequestId");

                    b.HasIndex("ArchiveDocumentId", "RequestedAt");

                    b.HasIndex("Status", "RequestedAt");

                    b.ToTable("ArchiveFulfillments", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveIngestionBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataChecksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MetadataFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordsDiscovered")
                        .HasColumnType("int");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("RecordsTransferred")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("MetadataFilePath", "MetadataChecksum")
                        .IsUnique();

                    b.ToTable("ArchiveIngestionBatches", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.EmployeeArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KellyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskedTaxId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StorageStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("KellyId")
                        .IsUnique();

                    b.ToTable("EmployeeArchives", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollDataRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ConfirmedEmployeeArchiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KellyId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestedDocumentTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SearchInitiatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SpecialistNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TaxIdLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedEmployeeArchiveId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeEmail", "SubmittedAt");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("PayrollDataRequests", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollRequestCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeArchiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchedAttributes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PayrollDataRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeArchiveId");

                    b.HasIndex("PayrollDataRequestId", "EmployeeArchiveId")
                        .IsUnique();

                    b.ToTable("PayrollRequestCandidates", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollRequestDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchiveDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PayrollDataRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveDocumentId");

                    b.HasIndex("PayrollDataRequestId", "ArchiveDocumentId")
                        .IsUnique();

                    b.ToTable("PayrollRequestDocuments", (string)null);
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveAuditEvent", b =>
                {
                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.ArchiveDocument", "ArchiveDocument")
                        .WithMany()
                        .HasForeignKey("ArchiveDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.EmployeeArchive", "EmployeeArchive")
                        .WithMany()
                        .HasForeignKey("EmployeeArchiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArchiveDocument");

                    b.Navigation("EmployeeArchive");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveDocument", b =>
                {
                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.EmployeeArchive", "EmployeeArchive")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeArchiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.ArchiveIngestionBatch", "IngestionBatch")
                        .WithMany("Documents")
                        .HasForeignKey("IngestionBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeArchive");

                    b.Navigation("IngestionBatch");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveFulfillment", b =>
                {
                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.ArchiveDocument", "ArchiveDocument")
                        .WithMany()
                        .HasForeignKey("ArchiveDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KellyServices.PARS.Domain.Entities.Requests.PayrollDataRequest", "PayrollDataRequest")
                        .WithMany()
                        .HasForeignKey("PayrollDataRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArchiveDocument");

                    b.Navigation("PayrollDataRequest");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollDataRequest", b =>
                {
                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.EmployeeArchive", "ConfirmedEmployeeArchive")
                        .WithMany()
                        .HasForeignKey("ConfirmedEmployeeArchiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfirmedEmployeeArchive");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollRequestCandidate", b =>
                {
                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.EmployeeArchive", "EmployeeArchive")
                        .WithMany()
                        .HasForeignKey("EmployeeArchiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KellyServices.PARS.Domain.Entities.Requests.PayrollDataRequest", "PayrollDataRequest")
                        .WithMany("Candidates")
                        .HasForeignKey("PayrollDataRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeArchive");

                    b.Navigation("PayrollDataRequest");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollRequestDocument", b =>
                {
                    b.HasOne("KellyServices.PARS.Domain.Entities.Archive.ArchiveDocument", "ArchiveDocument")
                        .WithMany()
                        .HasForeignKey("ArchiveDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KellyServices.PARS.Domain.Entities.Requests.PayrollDataRequest", "PayrollDataRequest")
                        .WithMany("Documents")
                        .HasForeignKey("PayrollDataRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveDocument");

                    b.Navigation("PayrollDataRequest");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.ArchiveIngestionBatch", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Archive.EmployeeArchive", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("KellyServices.PARS.Domain.Entities.Requests.PayrollDataRequest", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
